# Problem 1 

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
v = np.array([12,34,56,43,7])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
print(v)
v.sort()
print(v)

[12 34 56 43  7]
[ 7 12 34 43 56]


# Problem 2

In [11]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
a = np.array([10,15,30,45,60])
print("(1)", a, "\n")
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
b = np.arange(5,16)
print("(2)", b, "\n")
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
c = np.arange(50,101,5)
print("(3)", c, "\n")
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
d = np.zeros(10)
print("(4)", d, "\n")
# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
e = np.ones(10)
print("(5)", e, "\n")
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
f = np.linspace(0,100,5)
print("(6)", f, "\n")
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
g = np.random.randint(10,30,5)
print("(7)", g, "\n")
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
h = np.random.uniform(-1, 1, 10)
print("(8)", h, "\n")
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
i = np.random.randint(10,50,15)
i2 = i.reshape(3,5)
print("(9)", i2, "\n")
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
satir = np.sum(i2, axis=1)
sutun = np.sum(i2, axis=0)
print("(10)", f"satir toplam: {satir}")
print(f"sutun toplam: {sutun}")
print("\n")
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
max_value = np.max(i2)
min_value = np.min(i2)
mean_value = np.mean(i2)
print(f"(11) max: {max_value}\n")
print(f"min: {min_value}\n")
print(f"average: {mean_value}\n")
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
ind = np.unravel_index(np.argmax(i2),i2.shape)
print(f"(12) {ind}")
# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
j = np.arange(10,21)
j2 = j[0:3]
print("(13)", j2, "\n")
# 14- Üretilen dizinin elemanlarını tersten yazdırın.
j3 = j[::-1]
print("(14)", j3, "\n")
# 15- Üretilen matrisin ilk satırını seçiniz.
print(f"(15) {i2[0]} \n")
# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(f"(16) {i2[1,2]} \n")
# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(f"(17) {i2[0,0] , i2[1,0] , i2[2,0]} \n")
# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(f"[18] {i2 ** 2} \n")
# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
k = np.random.randint(-50, 50, 15)
print(f"(19) {k[k > 0]}")

(1) [10 15 30 45 60] 

(2) [ 5  6  7  8  9 10 11 12 13 14 15] 

(3) [ 50  55  60  65  70  75  80  85  90  95 100] 

(4) [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

(5) [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

(6) [  0.  25.  50.  75. 100.] 

(7) [27 21 10 19 21] 

(8) [ 0.23872807  0.34020151  0.44702698 -0.8834505  -0.51610664 -0.40551907
 -0.96380662  0.57263526  0.80033646  0.47095535] 

(9) [[26 45 38 36 40]
 [11 20 28 12 46]
 [15 11 39 30 27]] 

(10) satir toplam: [185 117 122]
sutun toplam: [ 52  76 105  78 113]


(11) max: 46

min: 11

average: 28.266666666666666

(12) (np.int64(1), np.int64(4))
(13) [10 11 12] 

(14) [20 19 18 17 16 15 14 13 12 11 10] 

(15) [26 45 38 36 40] 

(16) 28 

(17) (np.int32(26), np.int32(11), np.int32(15)) 

[18] [[ 676 2025 1444 1296 1600]
 [ 121  400  784  144 2116]
 [ 225  121 1521  900  729]] 

(19) [44 43 45 30 10 11 45]
