# Problem 1 

In [1]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
v = np.array([12,34,56,43,7])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
print(v)
v.sort()
print(v)

[12 34 56 43  7]
[ 7 12 34 43 56]


# Problem 2

In [13]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
a = np.array([10,15,30,45,60])
print(a, "\n")
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
b = np.arange(5,16)
print(b, "\n")
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
c = np.arange(50,101,5)
print(c, "\n")
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
d = np.zeros(10)
print(d, "\n")
# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
e = np.ones(10)
print(e, "\n")
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
f = np.linspace(0,100,5)
print(f, "\n")
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
g = np.random.randint(10,30,5)
print(g, "\n")
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
h = np.random.uniform(-1, 1, 10)
print(h, "\n")
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
i = np.random.randint(10,50,15)
i2 = i.reshape(3,5)
print(i2, "\n")
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
satir = np.sum(i2, axis=1)
sutun = np.sum(i2, axis=0)
print(f"satir toplam: {satir}")
print(f"sutun toplam: {sutun}")
print("\n")
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?


# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?


# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
j = np.arange(10,21)
j2 = j[0:3]
print(j2, "\n")
# 14- Üretilen dizinin elemanlarını tersten yazdırın.
j3 = j[::-1]
print(j3, "\n")
# 15- Üretilen matrisin ilk satırını seçiniz.


# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?


# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.


# 18- Üretilen matrisin her bir elemanının karesini alınız.


# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.


[10 15 30 45 60] 

[ 5  6  7  8  9 10 11 12 13 14 15] 

[ 50  55  60  65  70  75  80  85  90  95 100] 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[  0.  25.  50.  75. 100.] 

[27 15 29 19 28] 

[-0.92137687  0.48261955 -0.66289906  0.14608519 -0.56516319 -0.48176688
 -0.55466828 -0.26054711  0.83241765 -0.27260786] 

[[17 43 26 22 41]
 [31 46 19 46 33]
 [31 18 17 15 49]] 

satir toplam: [149 175 130]
sutun toplam: [ 79 107  62  83 123]


[10 11 12] 

[20 19 18 17 16 15 14 13 12 11 10] 

