# Problem 1

In [5]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
v = np.random.randint(0,10,5)
# 3 - matris'in boyutunu öğrenin
print("boyut: ", v.shape)
# 4 - matris'i yeniden boyutlandırın
z = v.reshape(1,5)
print(z, "\n")
# 5 - matris'in boyut sayısını öğrenin
print("boyut sayısı(v): ", v.ndim)
print("boyut sayısı(z): ", z.ndim)

boyut:  (5,)
[[5 8 8 2 3]] 

boyut sayısı(v):  1
boyut sayısı(z):  2


# Problem 2

In [9]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
a = np.arange(0,11,2)
print(a)
# 2 - Oluşturduğunuz matrisi parçalayın
x,y,z = np.split(a,[2,4])
print(x)
print(y)
print(z)
# 3 - Parçalanmış matrisleri birleştirin
print(np.concatenate([x,y,z]))

[ 0  2  4  6  8 10]
[0 2]
[4 6]
[ 8 10]
[ 0  2  4  6  8 10]


# Problem 3

In [11]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
n = np.arange(5, 101, 2)
rn = np.random.choice(n,10)
print(rn)
# 2 - matris'in özelliklerini inceleyin
print(rn.shape)
print(rn.ndim)
print(rn.size)
print(rn.dtype)

[19 67 55 39 21 73 81 49 87 17]
(10,)
1
10
int64
