# NUMPY

- Numpy, sayısal işlemleri hızlı yapmak için C dili ile yazılmış bir Python kütüphanesidir.
- Veri analizinde kullanılır.
- Bilgisayara kurmak için pip install numpy komudu kullanılır.
- Bilimsel hesaplamalar için kullanılır.
- Arrayler/ çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı işlemler yapabilir.
- Temmelleri 1995 yılında atıldı, ama nihai olarak 2005 yılında Travis Oliphant tarafından hayata geçirilmiştir.
- Listelere benzerdir. Fakat verimli veri saklama ve vektör işlemleri için Numpy kullanılır.

# NEDEN NUMPY??

In [1]:
# klasik yöntem

a = [1,2,3,4]
b = [2,3,4,5]
ab = []
for i in range(0, len(a)):
    ab.append(a[i] * b[i])

print(ab)

[2, 6, 12, 20]


In [2]:
# numpy ile
import numpy as np

a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
print(a*b)

[ 2  6 12 20]


.reshape() fonksiyonu ile arraylerin boyutlarını değiştirebiliriz.

In [3]:
x = np.array([1,2,3,4,5,6,7,8,9])
multi = x.reshape(3,3)
print(multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


.shape ile arrayin boyutunu öğrenebiliriz. !!!Dikkat parantezi yok

In [4]:
print(multi.shape)
print(x.shape)

(3, 3)
(9,)


.ndim ile arraylerin boyut sayısını öğrenebilirsin.

In [5]:
print(multi.ndim)
print(x.ndim)

2
1


# Birleştirme (Concatenation)

.concatenate() fonksiyonu ile birleştirme yapabiliriz.

In [6]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])

print(np.concatenate([x,y]))

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
z = np.array([11,12,13,14,15])
print(np.concatenate([x,y,z]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [8]:
a = np.array([[1,2,3],[4,5,6]])
print(np.concatenate([a,a]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


axis = 0 satır bazında birleştirme yapar

axis = 1 sütun bazında birleştirme yapar

In [9]:
print(np.concatenate([a,a], axis= 1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [10]:
print(np.concatenate([a,a], axis= 0))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


# Array Ayırma (Splitting)

.split() fonksiyonu ile array ayırma işlemi yapılabilir.

In [11]:
m = np.array([1,2,3,99,99,3,2,1])
print(np.split(m, [3,5]))

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]


In [12]:
a,b,c = np.split(m, [3,5])
print(a)
print(b)
print(c)

[1 2 3]
[99 99]
[3 2 1]


vsplit() fonksiyonu ile array yatay olarak ayırma işlemi yapabiliriz.

hsplit() fonksiyonu ile array dikey olarak ayırma işlemi yapabiliriz.

In [13]:
n = np.arange(16).reshape(4,4)
# 16 elemanı 1den 16ya kadar rastgele bir dizi olarak atamanı sağlıyor
np.vsplit(n,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [14]:
np.hsplit(n,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

### np.arange() 

- Belli bir aralıkta sayıları oluşturmak için kullanılır.
- np.arange(start, stop, step)

In [15]:
np.arange(3,12,2)

array([ 3,  5,  7,  9, 11])

### np.zeros()

Sıfırlardan oluşan bir numpy dizisi oluşturmak için kullanılır.

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

### np.ones()

Birlerden oluşan bir numpy dizisi oluşturmak için kullanılır.

In [17]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### np.linspace()

- Belli bir aralıkta sayıları oluşturmak için kullanılır.
- np.linspace(başlangıç, bitiş, bölünecek aralık)

In [18]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [19]:
np.random.randint(0,10,3)

array([0, 7, 2], dtype=int32)

In [20]:
np.random.randint(1,100,10)

array([57, 34, 39, 71, 14, 64, 64, 45, 12, 58], dtype=int32)

In [21]:
npArray = np.arange(50)
npMulti = npArray.reshape(5,10)

print(npMulti.sum(axis= 1))

[ 45 145 245 345 445]


# Numpy Arrayin Özellikleri

- ndim: boyut sayısı
- shape: boyut bilgisi
- size: toplam eleman sayısı
- dtype: veri tipi

In [22]:
a = np.random.randint(10, size= 10)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

1
(10,)
10
int32


# Array Sıralama (Sorting)

Array sıralama işlemleri yapmak için numpy kütüphanesinde yer alan sort() fonksiyonu kullanılır.

In [23]:
v = np.array([8,24,232,65,2,198])
print(v)
v.sort()
print(v)

[  8  24 232  65   2 198]
[  2   8  24  65 198 232]


In [24]:
m = np.random.normal(20,5,(3,3))
print(m)

[[24.78336125 17.29347109 23.21380017]
 [22.91330493 11.25099814 21.16801729]
 [11.28737768 15.76568263 15.78964644]]


In [26]:
print(np.sort(m, axis= 0)) #dikeyleri sıralıyor
print(np.sort(m, axis= 1)) #yatayları sıralıyor

[[11.28737768 11.25099814 15.78964644]
 [22.91330493 15.76568263 21.16801729]
 [24.78336125 17.29347109 23.21380017]]
[[17.29347109 23.21380017 24.78336125]
 [11.25099814 21.16801729 22.91330493]
 [11.28737768 15.76568263 15.78964644]]


# Index ile Elemanlara Erişmek

Aynı listelerde olduğu gibi indexlerle elemanlara erişebiliriz.

In [29]:
a = np.random.randint(10, size= 10)
print(a[0])
print(a[-1])

7
2


In [30]:
a[0] = 100
print(a)

[100   9   0   1   0   3   2   6   9   2]


In [31]:
x = np.random.randint(10, size= (3,5))
print(x)

[[7 1 8 7 1]
 [8 1 1 0 2]
 [9 4 6 4 2]]


In [33]:
print(x[0,0])
print(x[1,1])

7
1


In [34]:
x[1,4] = 100
print(x)

[[  7   1   8   7   1]
 [  8   1   1   0 100]
 [  9   4   6   4   2]]


In [35]:
x[-1,-1] = 3.14
print(x)

[[  7   1   8   7   1]
 [  8   1   1   0 100]
 [  9   4   6   4   3]]


# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [37]:
a = np.arange(20,30)
print(a)
print(a[0:3])
print(a[:3])
print(a[3:])
print(a[1::2])
print(a[0::2])
print(a[2::2])
print(a[1::5])


[20 21 22 23 24 25 26 27 28 29]
[20 21 22]
[20 21 22]
[23 24 25 26 27 28 29]
[21 23 25 27 29]
[20 22 24 26 28]
[22 24 26 28]
[21 26]


In [44]:
b = np.random.randint(10, size=[5,5])
print(b)
print(b[:,0], "\n") # tüm satırlardakı 0.sütüunlardaki elemanları al
print(b[:,1], "\n") # tüm satırlardakı 1.sütüunlardaki elemanları al
print(b[0,:], "\n") # tüm sütunlardaki 0.satırlardkai elemanları al
print(b[-1,:], "\n")
print(b[0:2,0:3], "\n")
print(b[::2,::2], "\n")

[[4 1 4 7 0]
 [6 9 5 5 3]
 [1 5 3 5 6]
 [5 7 0 7 2]
 [1 7 2 8 9]]
[4 6 1 5 1] 

[1 9 5 7 7] 

[4 1 4 7 0] 

[1 7 2 8 9] 

[[4 1 4]
 [6 9 5]] 

[[4 4 0]
 [1 3 6]
 [1 2 9]] 



# Alt Küme Üzerinde İşlem Yapmak

In [45]:
alt_b = b[0:3,0:2]
print(alt_b)

[[4 1]
 [6 9]
 [1 5]]


In [46]:
alt_b[0,0] = 100
alt_b[1,1] = 200
alt_b

array([[100,   1],
       [  6, 200],
       [  1,   5]], dtype=int32)

In [47]:
print(b)

[[100   1   4   7   0]
 [  6 200   5   5   3]
 [  1   5   3   5   6]
 [  5   7   0   7   2]
 [  1   7   2   8   9]]


# Fancy Index

Bir liste içine bu arrayden istediğimiz indexlerini koyarak o indexlerdeki verileri alabiliriz.

In [48]:
v = np.arange(0,30,3)
print(v)

[ 0  3  6  9 12 15 18 21 24 27]


In [49]:
yetgen = [1,3,5]
print(v[yetgen])

[ 3  9 15]


In [50]:
m = np.arange(9).reshape(3,3)
satir = np.array([0,1])
sutun = np.array([1,2])
print(m[satir,sutun])

[1 5]


# Koşullu Eleman İşlemleri

In [51]:
v = np.array([1,2,3,4,5])
print(v > 3)

[False False False  True  True]


In [53]:
print(v[v > 3])
print(v[v < 3])

[4 5]
[1 2]


In [54]:
print(v[v != 3])

[1 2 4 5]


In [55]:
print(v[v == 3])

[3]


# Matematiksel İşlemler

In [56]:
print(v * 2)

[ 2  4  6  8 10]


In [58]:
print(v + 10)

[11 12 13 14 15]


In [59]:
print(v * 5 / 10)

[0.5 1.  1.5 2.  2.5]


In [60]:
print(v ** 2)

[ 1  4  9 16 25]


In [61]:
print(np.subtract(v,3))

[-2 -1  0  1  2]


In [64]:
print(np.add(v,5))
print(np.multiply(v,5))
print(np.divide(v,5))
print(np.power(v,5))
print(np.mod(v,5))
print(np.absolute(v))


[ 6  7  8  9 10]
[ 5 10 15 20 25]
[0.2 0.4 0.6 0.8 1. ]
[   1   32  243 1024 3125]
[1 2 3 4 0]
[1 2 3 4 5]


In [67]:
print(np.sin(360))
print(np.log(10))

0.9589157234143065
2.302585092994046


In [68]:
?np

Type:        module
String form: <module 'numpy' from 'c:\\Users\\Hp\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\hp\appdata\local\programs\python\python312\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are i

# İki Bilinmeyenli Denklem Çözümü

In [70]:
# 5*x0 + x1 = 12
# x0 + 3*x1 = 10

a = np.array([[5,1],[1,3]])
b = np.array([12,10])
x = np.linalg.solve(a,b)
print(x)

[1.85714286 2.71428571]
